# Generated by Django 5.0.2 on 2024-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='Hello, world'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='your@example.com', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='shree', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='9858585959', max_length=10),
        ),
    ]
